# Generated by Django 5.1.6 on 2025-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_text_content_alter_post_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
    ]
