# Generated by Django 5.1.6 on 2025-07-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_share_id_alter_share_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set(),
        ),
    ]
